version: '3'
services:
  gdrive-downloader:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./downloads:/downloads
    environment:
      - FLASK_ENV=development
      - FLASK_APP=driveHog.py
      - GOOGLE_APPLICATION_CREDENTIALS=/DATA/AppData/gdown/kinetic-physics-391300-7da91d0c1c4c.json
      - SERVICE_ACCOUNT_FILE=/DATA/AppData/gdown/kinetic-physics-391300-7da91d0c1c4c.json
    command: >
      sh -c "flask run --host=0.0.0.0"
